version: '3.8'

services:
  app:
    build: .
    container_name: telegram_app
    command: tail -F /dev/null

    working_dir: /app/telegram_dbt_project # <--- ADD THIS LINE

    volumes:
      - .:/app
      - ./data/raw:/app/data/raw
      - ~/.dbt:/root/.dbt

    ports:
      - "8080:8080"

    env_file:
      - ./.env

    networks:
      - telegram_network

networks:
  telegram_network:
    driver: bridge