version: '3.8' # Specify the Docker Compose file format version

services:
  # Your Python application service
  app:
    build: . # Build the image using the Dockerfile in the current directory
    container_name: telegram_app
    command: tail -F /dev/null # Keep the container running for development, replace later

    volumes:
      - .:/app # Mount the current directory into the container's /app directory
      - ./data/raw:/app/data/raw # Explicitly mount raw data directory for persistence

    ports:
      - "8000:8000" # Map host port 8000 to container port 8000 (for FastAPI later)

    env_file:
      - ./.env # Load environment variables from the .env file

    networks:
      - telegram_network # Connect to a custom network

# --- REMOVED THE TOP-LEVEL 'volumes:' SECTION COMPLETELY ---
# Because there are no named volumes being defined anymore.
# Only service-specific bind mounts are used.

networks:
  telegram_network: # Define a custom network for services to communicate
    driver: bridge