# telegram_dbt_project/models/staging/sources.yml

version: 2

sources:
  - name: raw
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: raw # Use 'raw' schema, as created by load_raw_data.py

    tables:
      - name: telegram_messages
        identifier: telegram_messages

      - name: yolo_detections # <--- UPDATED NAME AND TYPE: Now a regular table
        description: "Raw JSON arrays of YOLO object detection results, loaded into PostgreSQL by load_raw_data.py."
        # No 'external' config, as it's a regular DB table